# Generated by Django 4.2.3 on 2023-10-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watchlist_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
    ]
