# Generated by Django 4.2.3 on 2023-10-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bidder_bid_user_remove_bid_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
